name: Continuous Integration

on: [push, pull_request]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # или ваша актуальная версия Node.js

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint # предполагая, что у вас есть команда lint в package.json

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # или ваша актуальная версия Node.js

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test # предполагая, что у вас есть команда test в package.json
